### ISSUE TITLE
Do golang CI Linting

### ISSUE THREAD

**Issue by lumjjb** [lumjjb/tornjak#47]
Fix golang ci linting to meet ci checks for

```
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
```
